<h2>CMSC 197 Quiz 1</h2>

<h4>Johanna Marie P. Quitoviera</h4>

In [13]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


<h3>Part 1</h3>

Create 2 1D arrays, y_hat and y

Initialize y_hat with 20 linearly spaced numbers between -1 and 1

In [23]:
y_hat = np.linspace(-1,1,20)
y_hat

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

Initialize y with 20 linearly spaced numbers between 0 and 1

In [25]:
y = np.linspace(0,1,20)
y

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Compute for the shape and dimension of y_hat and y.

In [26]:
#shape of y_hat
y_hat.shape

(20,)

In [28]:
#dimension of y_hat
y_hat.ndim

1

In [29]:
#shape of y
y.shape

(20,)

In [30]:
#dimension of y
y.ndim

1

Create individual functions for each of the loss functions with y and y_hat as parameters

Each function should return the loss value (L)

<h4>Mean Squared Error</h4>

In [38]:
def mse(y_hat, y):
    return np.mean(np.square(np.subtract(y_hat,y)))

mse(y_hat, y)

0.3421052631578948

<h4>Mean Absolute Error</h4>

In [37]:
def mae(y_hat, y):
    return np.mean(np.abs(np.subtract(y_hat,y)))

mae(y_hat, y)

0.4999999999999999

<h4>Mean Squared Logarithmic Error</h4>

In [46]:
def msle(y_hat, y):
    return np.mean(np.square(np.subtract(np.log(np.add(y_hat,1)),np.log(np.add(y,1)))))

msle(y_hat, y)

C:\Users\Admin\AppData\Local\Temp/ipykernel_13588/1185953933.py:2: RuntimeWarning: divide by zero encountered in log
  return np.mean(np.square(np.subtract(np.log(np.add(y_hat,1)),np.log(np.add(y,1)))))


inf

<h4>Mean Absolute Percentage Error</h4>

In [51]:
def mape(y_hat, y):
    return np.mean(np.abs(np.divide(np.subtract(y_hat,y),y)))*100

mape(y_hat, y)

C:\Users\Admin\AppData\Local\Temp/ipykernel_13588/170411890.py:2: RuntimeWarning: divide by zero encountered in true_divide
  return np.mean(np.abs(np.divide(np.subtract(y_hat,y),y)))*100


inf

<h3>Part 2</h3>

Create a 1d array M {1, 2, …16} using the arange function

In [9]:
M = np.arange(1,17)
M

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

Reshape M into 4x4 array and store it to N

In [10]:
N = M.reshape(4, 4)
N

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

Get the 2nd row of N

In [11]:
N[1]

array([5, 6, 7, 8])

Get the minimum values for each column of N

In [12]:
numpy.amin(N,axis=0)

array([1, 2, 3, 4])

Get the locations of the minimum values for each column of N

In [21]:
#get the indices of the minimum values from the 2D array N
loc = numpy.where(N == numpy.amin(N,axis=0))

#gather the coordinates of the minimum values
locList=list(zip(loc[0],loc[1]))
locList

[(0, 0), (0, 1), (0, 2), (0, 3)]

Get the average of the whole matrix

In [14]:
numpy.average(N, axis=None)

8.5

Create a vector V with 4 elements, each element is 1

In [15]:
V = np.ones(4, dtype=int)
V

array([1, 1, 1, 1])

Take the dot product of N and V

In [16]:
np.dot(N,V)

array([10, 26, 42, 58])